mixed-port: 7890
redir-port: 7892
authentication: [""]
allow-lan: true
mode: Rule
log-level: info
ipv6: false
external-controller: :9999
external-ui: ui
secret: 
tun: {enable: false}
experimental: {ignore-resolve-fail: true, interface-name: en0}
dns: {enable: true, ipv6: false, listen: 0.0.0.0:1053, use-hosts: true, enhanced-mode: redir-host, default-nameserver: [114.114.114.114, 223.5.5.5, 127.0.0.1:53], nameserver: [114.114.114.114, 223.5.5.5], fallback: [1.0.0.1, 8.8.4.4], fallback-filter: {geoip: true}}
store-selected: true
proxies:
  - {name: 🇰🇷 首尔_ARM, server: arm.rastyu.ml, port: 443, type: trojan, password: a2a8ff45-046c-4809-906f-797481ce520d, sni: arm.rastyu.ml, skip-cert-verify: true, udp: true}
  - {name: 🇸🇬 狮城_ARM, server: xin.rastyu.tk, port: 443, type: trojan, password: ff1ae45d-a0a1-4b2a-a41f-d426744359a2, sni: xin.rastyu.tk, skip-cert-verify: true, udp: true}
  - {name: 🇰🇷 首尔_备胎, server: test.rastyu.ml, port: 443, type: trojan, password: e5a7ad01-3864-4228-9e8e-139d12938212, sni: test.rastyu.ml, skip-cert-verify: true, udp: true}
proxy-groups:
  - name: 🚀 节点选择
    type: select
    proxies:
      - 🇰🇷 首尔_ARM
      - 🇸🇬 狮城_ARM
      - 🇰🇷 首尔_备胎
      - DIRECT
  - name: 🔰 手动切换
    type: select
    proxies:
      - 🇰🇷 首尔_ARM
      - 🇸🇬 狮城_ARM
      - 🇰🇷 首尔_备胎
      - DIRECT
  - name: 📠 电报消息
    type: select
    proxies:
      - 🚀 节点选择
      - 🇰🇷 首尔_ARM
      - 🇸🇬 狮城_ARM
      - 🇰🇷 首尔_备胎
      - 🔰 手动切换
  - name: 🎶 TikTok
    type: select
    proxies:
      - 🚀 节点选择
      - 🇰🇷 首尔_ARM
      - 🇸🇬 狮城_ARM
      - 🇰🇷 首尔_备胎
      - 🔰 手动切换
  - name: 🏰 迪士尼+
    type: select
    proxies:
      - 🚀 节点选择
      - 🇰🇷 首尔_ARM
      - 🇸🇬 狮城_ARM
      - 🇰🇷 首尔_备胎
      - 🔰 手动切换
  - name: 📺 油管视频
    type: select
    proxies:
      - 🚀 节点选择
      - 🇰🇷 首尔_ARM
      - 🇸🇬 狮城_ARM
      - 🇰🇷 首尔_备胎
      - 🔰 手动切换
  - name: 🎬 EMBY公益
    type: select
    proxies:
      - DIRECT
      - 🇰🇷 首尔_ARM
      - 🇸🇬 狮城_ARM
      - 🇰🇷 首尔_备胎
      - 🚀 节点选择
  - name: 📋 DIY名单
    type: select
    proxies:
      - DIRECT
      - 🇰🇷 首尔_ARM
      - 🇸🇬 狮城_ARM
      - 🇰🇷 首尔_备胎
      - 🚀 节点选择
  - name: 🍎 苹果服务
    type: select
    proxies:
      - DIRECT
      - 🇰🇷 首尔_ARM
      - 🇸🇬 狮城_ARM
      - 🇰🇷 首尔_备胎
      - 🚀 节点选择
  - name: Ⓜ️ 微软服务
    type: select
    proxies:
      - DIRECT
      - 🇰🇷 首尔_ARM
      - 🇸🇬 狮城_ARM
      - 🇰🇷 首尔_备胎
      - 🚀 节点选择
  - name: 🎮 游戏平台
    type: select
    proxies:
      - DIRECT
      - 🇰🇷 首尔_ARM
      - 🇸🇬 狮城_ARM
      - 🇰🇷 首尔_备胎
      - 🚀 节点选择
  - name: 🍿 奈飞视频
    type: select
    proxies:
      - 🚀 节点选择
      - 🇰🇷 首尔_ARM
      - 🇸🇬 狮城_ARM
      - 🇰🇷 首尔_备胎
      - 🔰 手动切换
  - name: 🎥 国外媒体
    type: select
    proxies:
      - 🚀 节点选择
      - 🇰🇷 首尔_ARM
      - 🇸🇬 狮城_ARM
      - 🇰🇷 首尔_备胎
      - 🔰 手动切换
  - name: 🏛️ 长城网络
    type: select
    proxies:
      - 🚀 节点选择
      - 🇰🇷 首尔_ARM
      - 🇸🇬 狮城_ARM
      - 🇰🇷 首尔_备胎
      - 🔰 手动切换
  - name: 🛡️ 应用净化
    type: select
    proxies:
      - REJECT
      - DIRECT
  - name: 🎯 全球直连
    type: select
    proxies:
      - DIRECT
      - 🇰🇷 首尔_ARM
      - 🇸🇬 狮城_ARM
      - 🇰🇷 首尔_备胎
      - 🔰 手动切换
  - name: 🐳 漏网之鱼
    type: select
    proxies:
      - DIRECT
      - 🇰🇷 首尔_ARM
      - 🇸🇬 狮城_ARM
      - 🇰🇷 首尔_备胎
      - 🔰 手动切换
rules:
 - DOMAIN-KEYWORD,tiktokcdn,🎶 TikTok
 - DOMAIN-SUFFIX,emby.wtf,🎬 EMBY公益
 - DOMAIN-SUFFIX,jmsooo.com,🎬 EMBY公益
 - DOMAIN-SUFFIX,fanart.tv,📋 DIY名单
 - DOMAIN-SUFFIX,tmdb.org,📋 DIY名单
 - DOMAIN-SUFFIX,themoviedb.org,📋 DIY名单
 - DOMAIN-SUFFIX,keeflys.com,📋 DIY名单
 - DOMAIN-SUFFIX,aptoide.com,📋 DIY名单
 - DOMAIN-SUFFIX,fast.com,📋 DIY名单
 - DOMAIN-SUFFIX,speedtest.net,📋 DIY名单
 - DOMAIN-SUFFIX,ooklaserver.net,📋 DIY名单
 - DOMAIN-SUFFIX,speed.cloudflare.com,📋 DIY名单
 - DOMAIN-SUFFIX,git.io,🏛️ 长城网络
 - DOMAIN,update.synology.com,🛡️ 应用净化
 - DOMAIN,update7.synology.com,🛡️ 应用净化
 - DOMAIN,autoupdate7.synology.com,🛡️ 应用净化
 - DOMAIN,autoupdate7.synology.cn,🛡️ 应用净化
 - GEOIP,CN,🎯 全球直连
 - MATCH,🐳 漏网之鱼
