---
mixed-port: 7893
redir-port: 7892
allow-lan: true
mode: rule
log-level: silent
ipv6: false
external-controller: 0.0.0.0:9090
external-ui: "/usr/share/openclash/ui"
secret: '123456'
dns:
  enable: true
  ipv6: false
  listen: 0.0.0.0:7874
  use-hosts: true
  enhanced-mode: redir-host
  default-nameserver:
  - 127.0.0.1:53
  - 192.168.10.1
  nameserver:
  - 192.168.10.1
  fallback:
  - https://dns.cloudflare.com/dns-query
  - tls://dns.google:853
  fallback-filter:
    geoip: true
store-selected: true
