#=================================================
# https://github.com/P3TERX/Actions-OpenWrt
# Description: Build OpenWrt using GitHub Actions

name: 4.LEDE_ARM电视盒子

on:
  repository_dispatch:
  workflow_dispatch:
    inputs:
      openwrt_board:
        description: "选择Amlogic主板"
        required: false
        default: "s905x3-hk1"
        type: choice
        options:
          - all
          - s905x3_s905d_s912
          - nanopi-r5c
          - nanopi-r5s
          - s922x
          - s905x3
          - s912
          - s905d
          - s905x3-hk1
          - s912-phicomm-t1
      openwrt_kernel:
        description: "选择kernel版本"
        required: false
        default: "5.15.1_6.1.1"
        type: choice
        options:
          - 5.4.1_5.10.1
          - 5.15.1_6.1.1
          - 5.4.1
          - 5.10.1
          - 5.15.1
          - 6.1.1
      auto_kernel:
        description: "自动打包最新kernel内核"
        required: false
        default: true
        type: boolean
      kernel_repo:
        description: "选择kernel内核仓库"
        required: false
        default: "ophub/kernel"
        type: choice
        options:
          - ophub/kernel
      openwrt_size:
        description: "设置rootfs大小(单位: MiB)"
        required: false
        default: "1024"

env:
  REPO_URL: https://github.com/coolsnowwolf/lede
  REPO_BRANCH: master
  CONFIG_FILE: router/HK1/box.config
  FEEDS_CONF: feeds.conf.default
  DIY_P1_SH: router/HK1/diy-part1.sh
  DIY_P2_SH: router/HK1/diy-part2.sh
  UPLOAD_RELEASE: true
  TZ: Asia/Shanghai
  FILE_NAME: LEDE_ARM_Box
  PRODUCT_NAME: LEDE_ARM_Box

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
    - name: 检查项目分支
      uses: actions/checkout@main
        
    - name: 安装编译环境
      env:
        DEBIAN_FRONTEND: noninteractive
      run: |
        docker rmi `docker images -q`
        sudo -E rm -rf /usr/share/dotnet /etc/mysql /etc/php /etc/apt/sources.list.d /usr/local/lib/android
        sudo -E apt -y purge azure-cli* docker* ghc* zulu* llvm* firefox google* dotnet* powershell* openjdk* mysql* php* mongodb* dotnet* snap* aspnetcore*
        [ -n "$AGENT_TOOLSDIRECTORY" ] && sudo rm -rf "$AGENT_TOOLSDIRECTORY"
        sudo -E apt update
        sudo -E apt -y install $(curl -fsSL https://is.gd/depends_ubuntu_2204)
        sudo -E apt -y autoremove --purge
        sudo -E systemctl daemon-reload
        sudo -E apt clean
        sudo timedatectl set-timezone "$TZ"
        sudo mkdir -p /workdir
        sudo chown $USER:$GROUPS /workdir
        echo "status=success" >> ${GITHUB_OUTPUT}
        df -Th

    - name: 下载固件源码
      working-directory: /workdir
      run: |
        df -hT $PWD
        git clone $REPO_URL -b $REPO_BRANCH openwrt
        ln -sf /workdir/openwrt $GITHUB_WORKSPACE/openwrt
        cd openwrt
        useVersionInfo=$(git show -s --date=short --format="Author: %an<br/>date: %cd<br/>commit: %s<br/>commit hash: %H")
        echo "useVersionInfo=$useVersionInfo" >> $GITHUB_ENV
        echo "DATE=$(date "+%Y-%m-%d %H:%M:%S")" >> $GITHUB_ENV

    - name: 加载自定义设置
      run: |
        [ -e $FEEDS_CONF ] && mv $FEEDS_CONF openwrt/feeds.conf.default
        chmod +x $DIY_P1_SH
        cd openwrt
        $GITHUB_WORKSPACE/$DIY_P1_SH

    - name: 下载插件
      run: cd openwrt && ./scripts/feeds update -a

    - name: 读取插件
      run: cd openwrt && ./scripts/feeds install -a

    - name: 更改设置
      run: |
        [ -e files ] && mv files openwrt/files
        [ -e $CONFIG_FILE ] && mv $CONFIG_FILE openwrt/.config
        chmod +x $DIY_P2_SH
        cd openwrt
        $GITHUB_WORKSPACE/$DIY_P2_SH

    - name: 下载安装包
      id: package
      run: |
        cd openwrt
        make defconfig
        make download -j8
        find dl -size -1024c -exec ls -l {} \;
        find dl -size -1024c -exec rm -f {} \;
        rm -rf $GITHUB_WORKSPACE/.git
        rm -rf $GITHUB_WORKSPACE/opt
        df -Th

    - name: 开始编译固件
      id: compile
      run: |
        cd openwrt
        echo -e "$(nproc) thread compile"
        make -j$(nproc) || make -j1 || make -j1 V=s
        echo "status=success" >> ${GITHUB_OUTPUT}
        grep '^CONFIG_TARGET.*DEVICE.*=y' .config | sed -r 's/.*DEVICE_(.*)=y/\1/' > DEVICE_NAME
        [ -s DEVICE_NAME ] && echo "DEVICE_NAME=_$(cat DEVICE_NAME)" >> $GITHUB_ENV
        echo "FILE_TIME=$(date "+%Y年%m月%d日%H点")" >> $GITHUB_ENV

    - name: 发布至release
      uses: ncipollo/release-action@main
      if: steps.compile.outputs.status == 'success' && !cancelled()
      with:
        name: R${{ env.FILE_TIME }} for ${{ env.PRODUCT_NAME }}
        tag: ${{ env.FILE_NAME }}
        artifacts: openwrt/bin/targets/*/*/*rootfs.tar.gz
        allowUpdates: true
        removeArtifacts: true
        token: ${{ secrets.RELEASES_TOKEN }}

    - name: 清理空间
      if: steps.compile.outputs.status == 'success' && !cancelled()
      run: |
        cd openwrt/
        rm -rf $(ls . | grep -v "^bin$" | xargs) 2>/dev/null
        df -hT ${PWD}

    - name: 打包内核固件
      if: steps.compile.outputs.status == 'success' && !cancelled()
      uses: ophub/amlogic-s9xxx-openwrt@main
      with:
        openwrt_path: openwrt/bin/targets/*/*/*rootfs.tar.gz
        openwrt_board: ${{ inputs.openwrt_board }}
        openwrt_kernel: ${{ inputs.openwrt_kernel }}
        auto_kernel: ${{ inputs.auto_kernel }}
        kernel_repo: ${{ inputs.kernel_repo }}
        openwrt_size: ${{ inputs.openwrt_size }}
        gh_token: ${{ secrets.RELEASES_TOKEN }}

    - name: 发布至release
      uses: ncipollo/release-action@main
      if: ${{ env.PACKAGED_STATUS }} == 'success' && !cancelled()
      with:
        name: ${{ env.FILE_TIME }} for ${{ env.PRODUCT_NAME }}
        tag: ${{ env.FILE_NAME }}
        artifacts: ${{ env.PACKAGED_OUTPUTPATH }}/*
        allowUpdates: true
        removeArtifacts: true
        token: ${{ secrets.RELEASES_TOKEN }}
        body: |
          - 晶晨 s9xxx 电视盒子Openwrt固件
          - 默认IP：192.168.10.10 默认密码：password
          - 默认WIFI名称: OpenWrt 默认密码：none
          - Install to EMMC: Login to OpenWrt → System → Amlogic Service → Install OpenWrt
          - 当前使用版本:【编译前的最后一次[➦主源码](https://github.com/coolsnowwolf/lede)更新记录】
          ${{ env.useVersionInfo }}
            
    - name: 电报消息提醒
      run: |
        MSG="
        编译时间: ${{ env.FILE_TIME }}
        编译架构: ${{ env.PRODUCT_NAME }}固件
        下载地址: https://github.com/rastyu/s905x3-openwrt/releases/tag/${{ env.FILE_NAME }}
        "
        curl "https://api.telegram.org/bot${{ secrets.TELEGRAM_TOKEN }}/sendMessage" -d "chat_id=${{ secrets.TELEGRAM_TO }}&text=${MSG}"
