name: Build NPM

on:
  repository_dispatch:
  workflow_dispatch:

jobs:
  push:
    runs-on: ubuntu-latest
    steps:
      - 
        name: Checkout
        uses: actions/checkout@master

      - name: Set Version
        id: set-version
        run: |
          echo "::set-output name=version::${GITHUB_REF:10}"
          echo "ReleaseTag=${GITHUB_REF:10}"

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - 
        name: Build MediaServerTools
        uses: docker/build-push-action@v3
        with:
          context: ./docker/
          file: ./docker/Dockerfile
          platforms: |
            linux/amd64
          push: true
          build-args: |
            VERSION=${{ steps.set-version.outputs.version }}
          tags: |
             ${{ secrets.DOCKER_USERNAME }}/NPM:${{ steps.set-version.outputs.version }}
             ${{ secrets.DOCKER_USERNAME }}/NPM:latest
             
      -
        name: Docker Hub Description
        uses: peter-evans/dockerhub-description@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          repository: rastyu/NPM
          short-description: NPM Image
          readme-filepath: ./docker/README.md
