#==========================================================================
# https://github.com/ophub/amlogic-s9xxx-armbian
# Description: Automatically delete older releases and workflows
#==========================================================================

name: e.删除旧 releases & workflow

on:
  repository_dispatch:
  workflow_dispatch:

env:
  DELETE_RELEASE: false
  DELETE_ARTIFACTS: true
  KEEP_DAY: 1
  KEEP_MININUM_RUNS: 1
  KEEP_MININUM_RELEASE: 9

jobs:
  build:
    runs-on: ubuntu-22.04
    if: ${{ github.event.repository.owner.id }} == ${{ github.event.sender.id }}
    steps:
    - name: 检查项目分支
      uses: actions/checkout@v3
      
    - name: 检测分配的服务器性能
      run: |
        echo "已知性能较强CPU型号：8171M>8272CL>E5-2673 v3>8370C,"
        echo -e "-------------- ------------CPU信息------------------------------------------\n"
        echo "CPU物理数量:$(cat /proc/cpuinfo| grep "physical id"| sort| uniq| wc -l)"
        echo -e "CPU核心及版本信息：$(cat /proc/cpuinfo | grep name | cut -f2 -d: | uniq -c) \n"
        echo "-------------------------------内存信息-------------------------------------------"
        echo "已安装内存详细信息："
        sudo lshw -short -C memory | grep GiB
        echo -e "\n"
        echo "-----------------------------硬盘信息---------------------------------------------"
        echo -e  "硬盘数量：$(ls /dev/sd* | grep -v [1-9] | wc -l) \n"
        echo "硬盘详情："
        df -Th
        
    - name: 清理空间
      run: |
        cd openwrt/
        rm -rf $(ls . | grep -v "^bin$" | xargs) 2>/dev/null
        df -hT ${PWD}
        
#    - name: cache缓存工具链
#      uses: klever1988/cachewrtbuild@main
#      with:
#        ccache: 'flase'
#        clean: 'true'
#        prefix: ${{ github.workspace }}/openwrt
        
    - name: 清理旧的Releases
      uses: codesnas/delete-older-releases@main
      if: env.DELETE_RELEASE == 'true'
      with:
        keep_latest: ${{ env.KEEP_MININUM_RELEASE }}
        delete_tags: true
      env:
        GITHUB_TOKEN: ${{ secrets.RELEASES_TOKEN }}

    - name: 清理旧的workflow
      uses: Mattraks/delete-workflow-runs@main
      if: env.DELETE_ARTIFACTS == 'true'
      with:
        token: ${{ secrets.RELEASES_TOKEN }}
        repository: ${{ github.repository }}
        retain_days: ${{ env.KEEP_DAY }}
        keep_minimum_runs: ${{ env.KEEP_MININUM_RUNS }}
