#==========================================================================
# https://github.com/ophub/amlogic-s9xxx-armbian
# Description: Automatically delete older releases and workflows
#==========================================================================

name: e.删除旧 releases & workflow

on:
  repository_dispatch:
  workflow_dispatch:

env:
  DELETE_RELEASE: false
  DELETE_ARTIFACTS: true
  KEEP_DAY: 1
  KEEP_MININUM_RUNS: 1
  KEEP_MININUM_RELEASE: 9

jobs:
  build:
    runs-on: ubuntu-22.04
    if: ${{ github.event.repository.owner.id }} == ${{ github.event.sender.id }}
    steps:
    - name: 检查项目分支
      uses: actions/checkout@v3

    - name: 清理旧的Releases
      uses: codesnas/delete-older-releases@main
      if: env.DELETE_RELEASE == 'true'
      with:
        keep_latest: ${{ env.KEEP_MININUM_RELEASE }}
        delete_tags: true
      env:
        GITHUB_TOKEN: ${{ secrets.RELEASES_TOKEN }}

    - name: 清理旧的workflow
      uses: Mattraks/delete-workflow-runs@main
      if: env.DELETE_ARTIFACTS == 'true'
      with:
        token: ${{ secrets.RELEASES_TOKEN }}
        repository: ${{ github.repository }}
        retain_days: ${{ env.KEEP_DAY }}
        keep_minimum_runs: ${{ env.KEEP_MININUM_RUNS }}
